spring:
  profiles:
    active: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    jedis:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 2000
        max-wait: -1
server:
  tomcat:
    uri-encoding: UTF-8
# twilio config
twilio:
  accountSid: AC147c8ad10b7467f1e17b4da63bbf2fec
#  accountSid: AC78d701a6c62260711c507cd3510872b8
  authToken: 9250418056a421f0ab7839c45c1f6d37
#  authToken: 5902b7f33bb1de4c13dcbfda295b657f
  msgUrl: https://13430596.ngrok.io/twilio/receive-message
  msgStatusCallback: https://13430596.ngrok.io/twilio/message-status-callback
  viewFileUrl: https://13430596.ngrok.io/file/view
