spring:
  profiles:
    active: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    timeout: 10s
    jedis:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 2000
        max-wait: -1
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  mail:
    protocol: smtp
    password: 1qaz2wsx
    port: 25
    default-encoding: UTF-8
    host: smtp.163.com
    username: ytkj_2019@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  tomcat:
    uri-encoding: UTF-8
# twilio config
twilio:
  accountSid: AC147c8ad10b7467f1e17b4da63bbf2fec
  #accountSid: AC1da9cfc9e0987ca53d158ebabcd9bbe9
  authToken: 9250418056a421f0ab7839c45c1f6d37
  #authToken: 5b4c21f95986aa7d5dc79eb9b304f049
  #msgUrl: http://sms.duopin360.com/twilio/receive-message
  #msgStatusCallback: http://sms.duopin360.com/twilio/message-status-callback
  #viewFileUrl: http://sms.duopin360.com/file/view
  planExecTimeDelay: 2  # minutes
  singleThreadSendNum: 1000

logging:
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} %-5level %logger- %msg%n"
  file: logs/log.log
  level:
    com.adbest.smsmarketingfront: info
mobilePrice:
  free: 2
  ordinary: 1