server:
  port: 8087
  servlet:
    session:
      timeout: 2h
  tomcat:
    basedir: /tmp/tomcat

spring:
  banner:
    charset: UTF-8
  datasource:
    url: jdbc:mysql://10.0.10.46:3306/sms_marketing?useSSL=false&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: messaging-ro
    password: V@koDa11as
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
encrypt:
  salt:
    password: Aasda65asd58wd
web:
  login: http://text.vokophone.com/login
twilio:
  msgUrl: http://text.vokophone.com/twilio/receive-message
  msgStatusCallback: http://text.vokophone.com/twilio/message-status-callback
  viewFileUrl: http://text.vokophone.com/file/view